print("hello")
print('hello')
print("we're friends")
print('hello "achraf"')
print(5)
print(int('8') + 5)
print(float('10.5')+6)
print("hello " + "friends")
print("hello " + str(5))
print(int("h") + 5)
